### ISSUE TITLE
Add atomWithRefresh

### ISSUE THREAD

**Issue by CeliaLfd** [Fattafatta/rescript-jotai#22]
Hello @Fattafatta 👋 

Would it be possible to add `atomWithRefresh`?
https://jotai.org/docs/utilities/resettable#atomwithrefresh

Thanks!

**Comment by Fattafatta** [comment]
Version `0.4.2`was just released and it includes `AtomWithRefresh`.

You can create a read-only atom like this:

```rescript
let atom = Jotai.Utils.AtomWithRefresh.make(({get}) => 1)
```

To trigger a refresh a dedicated hook has to be used:

```rescript
let (value, refresh) = Jotai.Utils.useRefreshAtom(atom)
refresh()
```

For a writable atom use:

```rescript
let atom = Jotai.Utils.AtomWithRefresh.makeComputed(
({get}) => 1,
({get, set}, arg) => {/* set something */},
)
let (value, update) = Jotai.Utils.useAtom(atom)
```

**Comment by CeliaLfd** [comment]
Thanks for your work 🙏
