### ISSUE TITLE
makeComputed doesn't work/has type error

### ISSUE THREAD

**Issue by MatusT** [Fattafatta/rescript-jotai#5]
Hi, I am new to ReScript so I don't fully understand what problem the type system has but this is the error I get:
```
FAILED: src/Storage.cmj

  We've found a bug for you!
  C:\Projects\interactive-debugger\src\Storage.res:2:5-9

  1 │ let atom1 = Jotai.Atom.make(1)
  2 │ let atom2 = Jotai.Atom.makeComputed(({get}) => get(atom1) + 1)
  3 │ let atom3 = Jotai.Atom.makeComputed(({get}) => get(atom1) + get(atom2) +
    │  1)
  4 │

  This expression's type contains type variables that can't be generalized:
  Jotai.Atom.t<int, Jotai.Atom.Actions.t<'_weak1>, Jotai.Atom.Tags.r>

  This happens when the type system senses there's a mutation/side-effect,
  in combination with a polymorphic value.
  Using or annotating that value usually solves it.

FAILED: cannot make progress due to previous errors.
```
when trying out the makeComputed example
```
let atom1 = Jotai.Atom.make(1)
let atom2 = Jotai.Atom.makeComputed(({get}) => get(atom1) + 1)
let atom3 = Jotai.Atom.makeComputed(({get}) => get(atom1) + get(atom2) + 1)
```

Annotating the types:
```
let atom1: Jotai.Atom.t<int, _, _> = Jotai.Atom.make(1)
let atom2: Jotai.Atom.t<int, _, _> = Jotai.Atom.makeComputed(({get}) => get(atom1) + 1)
```
does not help.

**Comment by Fattafatta** [comment]
I can see no error in your code. I tested the same code on my machine and it works fine. When you check the `Atom_test.res` file in the repo you can also see that there is a test specific for the `makeComputed` function (without annotation).

So something else must go wrong here. Can you post your `bsconfig.json` and `package.json`? Then I can try to reproduce your problem.

**Comment by Fattafatta** [comment]
I found a fix for now. The problematic part is the `_weak` annotation in your error message. This means that the compiler is unable to find the correct type itself. If you also annotate the second part it works:
```
let atom1 = Jotai.Atom.make(1)
let atom2: Jotai.Atom.t<int, Jotai.Atom.Actions.t<int>, _> = Jotai.Atom.makeComputed(({get}) => get(atom1) + 1)
let atom3: Jotai.Atom.t<int, Jotai.Atom.Actions.t<int>, _> = Jotai.Atom.makeComputed(({get}) => get(atom1) + get(atom2) + 1)
```

I will do some research why this is suddenly a problem. In the past the second annotation was never necessary.

**Comment by Fattafatta** [comment]
Releases new version 0.1.3 that fixes this undesired behaviour. Now type annotation for the action should not be necessary for readonly atoms.
