### ISSUE TITLE
Add atomFamily

### ISSUE THREAD

**Issue by mcharnet** [Fattafatta/rescript-jotai#7]
Hi @Fattafatta, 

Thanks for these bindings ! Would it be possible to add `atomFamily` with async support ?

Thanks

**Comment by Fattafatta** [comment]
Hi @mcharnet,

`atomFamily` is now supported. You can find usage examples in the [README](https://github.com/Fattafatta/rescript-jotai#atomfamily-jotaiutilsatomfamily)

I'm not entirely sure what you mean by async support. Do you have an example?
